### ISSUE TITLE
ZeroNet update failed on ubuntu 18.04

### ISSUE THREAD

**Issue by rllola** [rllola/ZeronetBrowser#102]
The update through ZeroNet interface failed to work with ZeroNet Browser.

It shoud not be an issue because the code is not compile into binary and is readable.

However it seems to not find the proper repository or it is missing the `update.py` file ?

**Comment by rllola** [comment]
Haven't been able to reproduce it. I can launch the update process but it will open a new window when done. It should be avoid...

**Comment by rllola** [comment]
Still not working :

```
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 249, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "/usr/share/ZeronetBrowser/ZeroNet/zeronet.py", line 99, in start
    main()
  File "/usr/share/ZeronetBrowser/ZeroNet/zeronet.py", line 34, in main
    update.update()
  File "/usr/share/ZeronetBrowser/ZeroNet/update.py", line 76, in update
    os.makedirs(dest_dir)
  File "os.py", line 241, in makedirs
PermissionError: [Errno 13] Permission denied: '/usr/share/ZeronetBrowser/ZeroNet/src/lib/pyelliptic'
```

**Comment by rllola** [comment]
We would need a subcall with sudo to execute the `update.py` script or we can show a message and ask them to run `sudo ZeronetBrowser --update`...
