### ISSUE TITLE
Can't update to 0.7.1 on windows with the latest installer.

### ISSUE THREAD

**Issue by Noruka** [rllola/ZeronetBrowser#124]
When you try to update to 0.7.1 with updater.py (the official ZeroNet Py3 Updater) it brings up the terminal and just give websocket error with no end.

That if you use the implemented zeronet client.

If you use your own distribution and then use the browser with the client already running works fine.

**Comment by rllola** [comment]
Thank you for reporting it.

Are you using the latest version ? 

I think I also had this problem on linux and wasnt able to reproduce it.

**Comment by Noruka** [comment]
Yes, I am using the 0.2.5 Release for windows.

**Comment by rllola** [comment]
The problem seems to be the same that I had with linux : 
````
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "C:\Program Files (x86)\Zeronet Browser\ZeroNet\zeronet.py", line 99, in start
    main()
  File "C:\Program Files (x86)\Zeronet Browser\ZeroNet\zeronet.py", line 34, in main
    update.update()
  File "C:\Program Files (x86)\Zeronet Browser\ZeroNet\update.py", line 76, in update
    os.makedirs(dest_dir)
  File "os.py", line 221, in makedirs
PermissionError: [WinError 5] Accès refusé: 'C:\\Program Files (x86)\\Zeronet Browser\\ZeroNet/plugins/AnnounceBitTorrent'
```

When trying to update from 0.7.0 to 0.7.1
