### ISSUE TITLE
Can't run ZeroBrowser from Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by d14na** [rllola/ZeronetBrowser#5]
__No luck executing from build__

```
[11084] PyInstaller Bootloader 3.x
[11084] LOADER: executable is /home/dev/Downloads/ZeronetBrowser/build/browser/ZeronetBrowser
[11084] LOADER: homepath is /home/dev/Downloads/ZeronetBrowser/build/browser
[11084] LOADER: _MEIPASS2 is NULL
[11084] LOADER: archivename is /home/dev/Downloads/ZeronetBrowser/build/browser/ZeronetBrowser
[11084] LOADER: Extracting binaries
[11084] LOADER: Executing self as child
[11084] LOADER: set _MEIPASS2 to /home/dev/Downloads/ZeronetBrowser/build/browser
[11084] LOADER: LD_LIBRARY_PATH=/home/dev/Downloads/ZeronetBrowser/build/browser
[11084] LOADER: Registering signal handlers
[11085] PyInstaller Bootloader 3.x
[11085] LOADER: executable is /home/dev/Downloads/ZeronetBrowser/build/browser/ZeronetBrowser
[11085] LOADER: homepath is /home/dev/Downloads/ZeronetBrowser/build/browser
[11085] LOADER: _MEIPASS2 is /home/dev/Downloads/ZeronetBrowser/build/browser
[11085] LOADER: archivename is /home/dev/Downloads/ZeronetBrowser/build/browser/ZeronetBrowser
[11085] LOADER: Already in the child - running user's code.
[11085] LOADER: Python library: /home/dev/Downloads/ZeronetBrowser/build/browser/libpython2.7.so.1.0
[11085] Error loading Python lib '/home/dev/Downloads/ZeronetBrowser/build/browser/libpython2.7.so.1.0': dlopen: /home/dev/Downloads/ZeronetBrowser/build/browser/libpython2.7.so.1.0: cannot open shared object file: No such file or directory
[11084] LOADER: Restoring signal handlers
[11084] LOADER: freeing args
[11084] LOADER: returning child exit status 255
[11084] LOADER: Back to parent (RC: 255)
[11084] LOADER: Doing cleanup
[11084] LOADER: Freeing archive status for /home/dev/Downloads/ZeronetBrowser/build/browser/ZeronetBrowser
```

__Also tried executing from dist__

```
dev@dev-VirtualBox:~/Downloads/ZeronetBrowser$ dist/ZeronetBrowser/ZeronetBrowser 
[11048] PyInstaller Bootloader 3.x
[11048] LOADER: executable is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/ZeronetBrowser
[11048] LOADER: homepath is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[11048] LOADER: _MEIPASS2 is NULL
[11048] LOADER: archivename is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/ZeronetBrowser
[11048] LOADER: Extracting binaries
[11048] LOADER: Executing self as child
[11048] LOADER: set _MEIPASS2 to /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[11048] LOADER: LD_LIBRARY_PATH=/home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[11048] LOADER: Registering signal handlers
[11049] PyInstaller Bootloader 3.x
[11049] LOADER: executable is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/ZeronetBrowser
[11049] LOADER: homepath is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[11049] LOADER: _MEIPASS2 is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[11049] LOADER: archivename is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/ZeronetBrowser
[11049] LOADER: Already in the child - running user's code.
[11049] LOADER: Python library: /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/libpython2.7.so.1.0
[11049] LOADER: Loaded functions from Python library.
[11049] LOADER: Manipulating environment (sys.path, sys.prefix)
[11049] LOADER: sys.prefix is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[11049] LOADER: Setting runtime options
[11049] LOADER: Initializing python
[11049] LOADER: Overriding Python's sys.path
[11049] LOADER: Post-init sys.path is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[11049] LOADER: Setting sys.argv
[11049] LOADER: setting sys._MEIPASS
[11049] LOADER: importing modules from CArchive
[11049] LOADER: extracted struct
[11049] LOADER: callfunction returned...
[11049] LOADER: extracted pyimod01_os_path
[11049] LOADER: callfunction returned...
[11049] LOADER: extracted pyimod02_archive
[11049] LOADER: callfunction returned...
[11049] LOADER: extracted pyimod03_importers
[11049] LOADER: callfunction returned...
[11049] LOADER: Installing PYZ archive with Python modules.
[11049] LOADER: PYZ archive: PYZ-00.pyz
[11049] LOADER: LC_CTYPE was C but resulted in NULL FileSystemDefaultEncoding
[11049] LOADER: Setting FileSystemDefaultEncoding to UTF-8 (was NULL)
[11049] LOADER: Running pyiboot01_bootstrap.py
[11049] LOADER: Running pyi_rth_pkgres.py
[11049] LOADER: Running pyi_rth_multiprocessing.py
[11049] LOADER: Running launch.py
Traceback (most recent call last):
  File "launch.py", line 5, in <module>
    from MainWindow import MainWindow
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "MainWindow.py", line 1, in <module>
    from Browser import Browser
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "Browser.py", line 1, in <module>
    import PyQt5
ImportError: No module named PyQt5
[11049] Failed to execute script launch
[11049] LOADER: OK.
[11049] LOADER: Cleaning up Python interpreter.
[11048] LOADER: Restoring signal handlers
[11048] LOADER: freeing args
[11048] LOADER: returning child exit status 255
[11048] LOADER: Back to parent (RC: 255)
[11048] LOADER: Doing cleanup
[11048] LOADER: Freeing archive status for /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/ZeronetBrowser
```

**Comment by rllola** [comment]
You need to execute from `dist` and not `build`. Be sure also to have `python-pyqt5` installed.

```
apt install python-pyqt5
```

**Comment by d14na** [comment]
__checked PyQt5__

```
apt install python-pyqt5

Building dependency tree       
Reading state information... Done
python-pyqt5 is already the newest version (5.10.1+dfsg-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
```

__but still...__

```
dev@dev-VirtualBox:~/Downloads/ZeronetBrowser/dist/ZeronetBrowser$ ./ZeronetBrowser

[12030] PyInstaller Bootloader 3.x
[12030] LOADER: executable is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/ZeronetBrowser
[12030] LOADER: homepath is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[12030] LOADER: _MEIPASS2 is NULL
[12030] LOADER: archivename is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/ZeronetBrowser
[12030] LOADER: Extracting binaries
[12030] LOADER: Executing self as child
[12030] LOADER: set _MEIPASS2 to /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[12030] LOADER: LD_LIBRARY_PATH=/home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[12030] LOADER: Registering signal handlers
[12031] PyInstaller Bootloader 3.x
[12031] LOADER: executable is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/ZeronetBrowser
[12031] LOADER: homepath is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[12031] LOADER: _MEIPASS2 is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[12031] LOADER: archivename is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/ZeronetBrowser
[12031] LOADER: Already in the child - running user's code.
[12031] LOADER: Python library: /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/libpython2.7.so.1.0
[12031] LOADER: Loaded functions from Python library.
[12031] LOADER: Manipulating environment (sys.path, sys.prefix)
[12031] LOADER: sys.prefix is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[12031] LOADER: Setting runtime options
[12031] LOADER: Initializing python
[12031] LOADER: Overriding Python's sys.path
[12031] LOADER: Post-init sys.path is /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser
[12031] LOADER: Setting sys.argv
[12031] LOADER: setting sys._MEIPASS
[12031] LOADER: importing modules from CArchive
[12031] LOADER: extracted struct
[12031] LOADER: callfunction returned...
[12031] LOADER: extracted pyimod01_os_path
[12031] LOADER: callfunction returned...
[12031] LOADER: extracted pyimod02_archive
[12031] LOADER: callfunction returned...
[12031] LOADER: extracted pyimod03_importers
[12031] LOADER: callfunction returned...
[12031] LOADER: Installing PYZ archive with Python modules.
[12031] LOADER: PYZ archive: PYZ-00.pyz
[12031] LOADER: LC_CTYPE was C but resulted in NULL FileSystemDefaultEncoding
[12031] LOADER: Setting FileSystemDefaultEncoding to UTF-8 (was NULL)
[12031] LOADER: Running pyiboot01_bootstrap.py
[12031] LOADER: Running pyi_rth_pkgres.py
[12031] LOADER: Running pyi_rth_multiprocessing.py
[12031] LOADER: Running launch.py
Traceback (most recent call last):
  File "launch.py", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "MainWindow.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "Browser.py", line 1, in <module>
ImportError: No module named PyQt5
[12031] Failed to execute script launch
[12031] LOADER: OK.
[12031] LOADER: Cleaning up Python interpreter.
[12030] LOADER: Restoring signal handlers
[12030] LOADER: freeing args
[12030] LOADER: returning child exit status 255
[12030] LOADER: Back to parent (RC: 255)
[12030] LOADER: Doing cleanup
[12030] LOADER: Freeing archive status for /home/dev/Downloads/ZeronetBrowser/dist/ZeronetBrowser/ZeronetBrowser
```

I don't get it, I'll give it a try on a different distro as soon as I get a chance.

**Comment by d14na** [comment]
I'm just gonna guess and say that this could be a __PATH__ issue, but I'm still not sure how to fix it. How would run from source using `python ...` and not the executable? Might provide some insight as to where the issue is.

**Comment by rllola** [comment]
You don't have to build it to try it. You ca just run `python launch.py` to get a look.

**Comment by rllola** [comment]
Could you also try to uninstall python-pyqt5 and reinstall it ? I also believe it is the path. Maybe by re-install it will add itself to the path.

**Comment by rllola** [comment]
Closing this issue because now you can just get the executable and don't have to build yourself.
